ContactDatabase/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using EdgeDB;
using Microsoft.AspNetCore.Identity;

namespace ContactDatabase.Pages;
public class IndexModel : PageModel
{
    private readonly EdgeDBClient _edgeclient;
    public IndexModel(EdgeDBClient client)
    {
        _edgeclient = client;
    }
    [BindProperty]
    public LoginInput LoginInput { get; set; }

    public async Task<IActionResult> OnPost()
    {
        string username = LoginInput.UserName;
        string password = LoginInput.Password;
        if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(password))
        {
            ModelState.AddModelError("", "username and password fields must be entered");
            return Page();
        }
        var query = @"SELECT Contact {username, password, role } FILTER Contact.username = <str>$username";
        var result = await _edgeclient.QueryAsync<Contact>(query, new Dictionary<string, object?>
        {
           { "username", LoginInput.UserName }
        });
        if(result.Count > 0)
        {
            var passwordHasher = new PasswordHasher<string>();
            var passwordVerificationResult = passwordHasher.VerifyHashedPassword(null, result.First().Password , LoginInput.Password);
            if (passwordVerificationResult==PasswordVerificationResult.Success)
            {
                    var claims = new List<Claim>
                    {
                       new Claim(ClaimTypes.Name, result.First().Username),
                       new Claim(ClaimTypes.Role, result.First().Role),
                    };
                    var scheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties = new AuthenticationProperties
                    {
                        AllowRefresh = true,
                        ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),

                    };
                    var user = new ClaimsPrincipal(claimsIdentity);
                    await HttpContext.SignInAsync(scheme, user, authProperties);
                    return RedirectToPage("/ContactList");
            }
            else
            {
               ModelState.AddModelError("", "Invalid password");
               return Page();
            }
        
        }
        else
        {
           ModelState.AddModelError("", "Unsuccessful login attempt ");
           return Page();
            
        }

    }

    public async Task<IActionResult> OnPostLoggingOut()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToPage("/Index");
    }
}
public class LoginInput
{
    public string UserName { get; set; }
    public string Password { get; set; }
}

ContactDatabase/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContactDatabase</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContactDatabase.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Contacts"> Add new contact</a>
                            </li>
                        }
                    </ul>
                    <form method="post"  asp-page ="/Index" asp-page-handler="LoggingOut">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <button type="submit" class="btn btn-primary">Logout</button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-primary" hidden>Logout</button>
                        }
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ContactDatabase - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>