ContactDatabase/Pages/ContactList.cshtml.cs
using EdgeDB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContactDatabase.Pages;

[BindProperties]
public class ContactListModel : PageModel
{
    private readonly EdgeDBClient _edgeclient;
    public List<Contact> ContactList { get; set; } = new();
    public List<Contact> NewContactList { get; set; } = new();
    public ContactListModel(EdgeDBClient client)
    {
        _edgeclient = client;
    }
    public async Task<IActionResult> OnGet()
    {
        var result = await _edgeclient.QueryAsync<Contact>("SELECT Contact {*} Order by .first_name;");
        ContactList = result.ToList();
        return Page();
    }

    public async Task<IActionResult> OnGetSearch(string searchValue)
    {
        var output = await _edgeclient.QueryAsync<Contact>("SELECT Contact {first_name,last_name,email,title,birth_date,description,marriage_status}  Order by .first_name;");
        ContactList = output.ToList();

        if (string.IsNullOrEmpty(searchValue))
        {
            var data = new { list = ContactList };
            return new JsonResult(data);
        }
        searchValue = searchValue.ToLower();
        foreach (var contact in ContactList)
        {
            if (contact.FirstName.ToLower().Contains(searchValue) || contact.LastName.ToLower().Contains(searchValue) || contact.Email.ToLower().Contains(searchValue))
            {
                NewContactList.Add(contact);
            }
        }
        var result = new { list = NewContactList };
        return new JsonResult(result);
    }

    public async Task<IActionResult> OnGetDelete(string contactId)
    {
        Guid newId = new Guid(contactId);
        var output = await _edgeclient.QueryAsync<Contact>("DELETE Contact FILTER .id = <uuid>$id", new Dictionary<string, object?> { { "id", newId } });
        var result = await _edgeclient.QueryAsync<Contact>("SELECT Contact {*} Order by .first_name;");
        ContactList = result.ToList();
        return new JsonResult(new { list = ContactList });
    }
}

ContactDatabase/Pages/Contacts.cshtml.cs
using EdgeDB;
using EdgeDB.DataTypes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Components.Forms;
using System.Security.Cryptography;

namespace ContactDatabase.Pages;

public class ContactsModel : PageModel
{

    private readonly EdgeDBClient _edgeclient;
    public ContactsModel(EdgeDBClient client)
    {
        _edgeclient = client;
    }
    
    [BindProperty]
    public Contact Contact { get; set; }
    public async Task<IActionResult> OnPost()
    {
        if(string.IsNullOrEmpty(Contact.FirstName) || string.IsNullOrEmpty(Contact.LastName) || string.IsNullOrEmpty(Contact.Email) || string.IsNullOrEmpty(Contact.Title) || string.IsNullOrEmpty(Contact.BirthDate.ToString())|| string.IsNullOrEmpty(Contact.MarriageStatus.ToString()))
        {
            ModelState.AddModelError("ContactError", "All fields must be filled");
            return Page();
        }
        var passwordHasher = new PasswordHasher<string>();
        Contact.Password = passwordHasher.HashPassword(null,Contact.Password );
        await AddContact(Contact);
        return RedirectToPage("/ContactList");
    }
    public async Task AddContact(Contact Contact)
    {
        var query = "INSERT Contact {username := <str>$username, password := <str>$password, role := <str>$role,first_name := <str>$first_name, last_name := <str>$last_name, email := <str>$email, title := <str>$title, birth_date := <datetime>$birth_date, description := <str>$description, marriage_status := <bool>$marriage_status}";
        await _edgeclient.ExecuteAsync(query, new Dictionary<string, object?>
        {
            {"username", Contact.Username},
            {"password", Contact.Password},
            {"role", Contact.Role},
            {"first_name", Contact.FirstName},
            {"last_name", Contact.LastName},
            {"email", Contact.Email},
            {"title", Contact.Title},
            {"birth_date", Contact.BirthDate},
            {"description", Contact.Description},
            {"marriage_status", Contact.MarriageStatus}
        });
    }
}
public class Contact
{
public Guid Id { get; set; }
public string FirstName { get; set; }
public string LastName { get; set; }
public string Email { get; set; }
public string Title { get; set; }
public DateTimeOffset BirthDate { get; set; }
public string Description { get; set; }
public bool MarriageStatus { get; set; }
public string Username { get; set; }
public string Password { get; set; }
public string Role { get; set; }

}

ContactDatabase/Pages/EditContact.cshtml.cs
using EdgeDB;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContactDatabase.Pages;
public class EditContactModel : PageModel
{
    private readonly EdgeDBClient _edgeclient;
    public EditContactModel(EdgeDBClient client)
    {
        _edgeclient = client;
    }
    [BindProperty]
    public Contact EditingContact { get; set; } = new Contact();

    public async Task<IActionResult> OnGetAsync(Guid id)
    {
        EditingContact = await _edgeclient.QuerySingleAsync<Contact>("SELECT Contact{*} FILTER .id = <uuid>$id", new Dictionary<string, object?> { { "id", id } });
        return Page();
    }

    public async Task<IActionResult> OnPostEditContact()
    {
        Guid id = Guid.Parse(Request.Form["id"]);
        EditingContact.Id = id;
        if (string.IsNullOrEmpty(EditingContact.FirstName) || string.IsNullOrEmpty(EditingContact.LastName) || string.IsNullOrEmpty(EditingContact.Email) || string.IsNullOrEmpty(EditingContact.Title) || string.IsNullOrEmpty(EditingContact.BirthDate.ToString()) || string.IsNullOrEmpty(EditingContact.Username) || string.IsNullOrEmpty(EditingContact.Password))
        {
            ModelState.AddModelError("ContactError", "All fields must be filled");
            return Page();
        }
        var passwordHasher = new PasswordHasher<string>();
        EditingContact.Password = passwordHasher.HashPassword(null, EditingContact.Password);
        await UpdateContact(EditingContact);
        return RedirectToPage("/ContactList");
    }
    public async Task UpdateContact(Contact EditingContact)
    {
        var query = "Update Contact FILTER .id = <uuid>$id SET {username := <str>$username, password := <str>$password, role := <str>$role,first_name := <str>$first_name, last_name := <str>$last_name, email := <str>$email, title := <str>$title, birth_date := <datetime>$birth_date, description := <str>$description, marriage_status := <bool>$marriage_status} ";
        await _edgeclient.ExecuteAsync(query, new Dictionary<string, object?>
        {
            {"id", EditingContact.Id},
            {"username", EditingContact.Username},
            {"password", EditingContact.Password},
            {"role", EditingContact.Role},
            {"first_name", EditingContact.FirstName},
            {"last_name", EditingContact.LastName},
            {"email", EditingContact.Email},
            {"title", EditingContact.Title},
            {"birth_date", EditingContact.BirthDate},
            {"description", EditingContact.Description},
            {"marriage_status", EditingContact.MarriageStatus}
        });
    }
}

ContactDatabase/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ContactDatabase.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ContactDatabase/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using EdgeDB;
using Microsoft.AspNetCore.Identity;

namespace ContactDatabase.Pages;
public class IndexModel : PageModel
{
    private readonly EdgeDBClient _edgeclient;
    public IndexModel(EdgeDBClient client)
    {
        _edgeclient = client;
    }
    [BindProperty]
    public LoginInput LoginInput { get; set; }

    public async Task<IActionResult> OnPost()
    {
        string username = LoginInput.UserName;
        string password = LoginInput.Password;
        if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(password))
        {
            ModelState.AddModelError("", "username and password fields must be entered");
            return Page();
        }
        var query = @"SELECT Contact {username, password, role } FILTER Contact.username = <str>$username";
        var result = await _edgeclient.QueryAsync<Contact>(query, new Dictionary<string, object?>
        {
           { "username", LoginInput.UserName }
        });
        if(result.Count > 0)
        {
            var passwordHasher = new PasswordHasher<string>();
            var passwordVerificationResult = passwordHasher.VerifyHashedPassword(null, result.First().Password , LoginInput.Password);
            if (passwordVerificationResult==PasswordVerificationResult.Success)
            {
                    var claims = new List<Claim>
                    {
                       new Claim(ClaimTypes.Name, result.First().Username),
                       new Claim(ClaimTypes.Role, result.First().Role),
                    };
                    var scheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties = new AuthenticationProperties
                    {
                        AllowRefresh = true,
                        ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),

                    };
                    var user = new ClaimsPrincipal(claimsIdentity);
                    await HttpContext.SignInAsync(scheme, user, authProperties);
                    return RedirectToPage("/ContactList");
            }
            else
            {
               ModelState.AddModelError("", "Invalid password");
               return Page();
            }
        
        }
        else
        {
           ModelState.AddModelError("", "Unsuccessful login attempt ");
           return Page();
            
        }

    }

    public async Task<IActionResult> OnPostLoggingOut()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToPage("/Index");
    }
}
public class LoginInput
{
    public string UserName { get; set; }
    public string Password { get; set; }
}

ContactDatabase/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContactDatabase.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ContactDatabase/Pages/ContactList.cshtml
@page "/ContactList"
@model ContactDatabase.Pages.ContactListModel
@{
}
<script src="https://unpkg.com/htmx.org@1.9.3" integrity="sha384-lVb3Rd/Ca0AxaoZg5sACe8FJKF0tnUgR2Kd7ehUOG5GCcROv5uBIZsOqovBAcWua" crossorigin="anonymous"></script>
@Html.AntiForgeryToken()
<div class="card" style="margin:19px;">
    <h2 style="text-align:center; padding:12px;">Contact List</h2>
</div>
<p style="padding-left:17px; font-weight:600"> you can search for a contact by entering first name , last name or email</p>
<div class="mb-3" style="margin-left:20px;  ">
    <div class="row">
        <div class="col-3">
            <form>
                <input type="text" id="searchby" onkeyup="getData()" style="width:400px;" placeholder=" search by first name , last name or email ..." />
            </form>
        </div>
    </div>
</div>

<div style="padding:20px;">
    <table class="table table-bordered table-striped">
        <thead style="background-color: cornflowerblue;">
            <tr>
                <th>
                    First name
                </th>
                <th>
                    Last name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Title
                </th>
                <th>
                    Description
                </th>
                <th>
                    Date of birth
                </th>
                <th>
                    Marriage status
                </th>
                @if (User.IsInRole("Admin"))
                {
                    <th>Actions</th>
                }
            </tr>
        </thead>
        <tbody id="myTable">
            @foreach (var item in Model.ContactList)
            {
                <tr>
                    <th>@item.FirstName</th>
                    <th>@item.LastName</th>
                    <th>@item.Email</th>
                    <th>@item.Title</th>
                    <th>@item.Description</th>
                    <th>@item.BirthDate</th>
                    <th>@(item.MarriageStatus ? "Yes" : "NO")</th>
                    @if(User.IsInRole("Admin"))
                    {
                        <th>
                            <div style="display: flex;">
                                <a asp-page="EditContact" asp-route-id="@item.Id" class="btn">Edit</a>
                                <a class="btn btn-red" onclick="deleteContact('@item.Id')">Delete</a>
                            </div>
                        </th>
                    }
                </tr>
            }
            <style>
                .btn{
                    text-decoration:none;
                    background-color:deeppink;
                    color:white;
                    margin-right:10px;
                }

                .btn-red{
                    text-decoration: none;
                    background-color: darkred;
                    color: white;
                }
            </style>
        </tbody>
    </table>
</div>

@section scripts
    {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        async function antiforgeryToken() {
            var response = await fetch("/antiforgerytoken", {
                method: "GET",
                credentials: 'include'
            });
            if (response.ok) {
                const xsrfToken = document.cookie
                    .split("; ")
                    .find(row => row.startsWith("XSRF-TOKEN="))
                    .split("=")[1];
                return xsrfToken;
            }
            else {
                return null;
            }
        }
        async function getData() {
            var searchbar = document.getElementById("searchby");
            var searchItem = searchbar.value;
            var tableContent = document.getElementById("myTable");
            var token = await antiforgeryToken();
            fetch(`/ContactList?handler=Search&searchValue=${encodeURIComponent(searchItem)}`, {
                headers: {
                    "RequestVerificationToken": $('input:hidden[name="__RequestVerificationToken"]').val(),
                    "X-XSRF-TOKEN": token
                },
            }).then(response => response.json())
                .then(data => {
                    var html = "";
                    html += "<style>.btn { background-color: deeppink; color: white; text-decoration: none; margin-right:10px;} .btn-red{background-color: darkred; color: white; text-decoration: none;} .delete{display:flex;}</style>";
                    for (const obj of data.list) {
                        html += "<tr><th>" + obj.firstName + "</th><th>" + obj.lastName + "</th><th>" + obj.email + "</th><th>" + obj.title + "</th><th>" + obj.description + "</th><th>" + obj.birthDate + "</th><th>" + (obj.marriageStatus ? "Yes" : "NO") + "</th><th> <div class='delete'><a href='/EditContact?id=" + obj.id + "' class='btn'>Edit</a> <a class='btn btn-red' onclick='deleteContact(\"" + obj.id + "\")'>Delete</a> </div> </th> </tr>";
                    }
                    tableContent.innerHTML = html;
                    
                }).catch(error => console.error(error));
        }

        async function deleteContact(id) {
            var tableContent = document.getElementById("myTable");
            var token = await antiforgeryToken();
            fetch(`/ContactList?handler=Delete&contactId=${encodeURIComponent(id)}`, {
                headers: {
                    "RequestVerificationToken": $('input:hidden[name="__RequestVerificationToken"]').val(),
                    "X-XSRF-TOKEN": token
                },
            }).then(response => response.json())
                .then(data => {
                    var html = "";
                    html += "<style>.btn { background-color: deeppink; color: white; text-decoration: none; margin-right:10px;} .btn-red{background-color: darkred; color: white; text-decoration: none;} .delete{display:flex;}</style>";
                    for (const obj of data.list) {
                        html += "<tr><th>" + obj.firstName + "</th><th>" + obj.lastName + "</th><th>" + obj.email + "</th><th>" + obj.title + "</th><th>" + obj.description + "</th><th>" + obj.birthDate + "</th><th>" + (obj.marriageStatus ? "Yes" : "NO") + "</th><th> <div class='delete'><a href='/EditContact?id=" + obj.id + "' class='btn'>Edit</a> <a class='btn btn-red' onclick='deleteContact(\"" + obj.id + "\")'>Delete</a> </div> </th> </tr>";
                    }
                    tableContent.innerHTML = html;

                }).catch(error => console.error(error));
        }
            
    </script>
}

ContactDatabase/Pages/Contacts.cshtml
@page "/Contacts"
@model ContactDatabase.Pages.ContactsModel
@{
}
<div class="row" >
    <div class="col-lg-9 mx-auto rounded border p-3">
        <h2 style="padding:15px;">New Contact</h2>
        <form method="post">
            <div class="firstname" style="margin:10px;">
                <label class="myfirstname" style="padding:10px;">First Name</label>
                <input type="text" name="Contact.FirstName" style="margin-left:44px;" required />
            </div>

            <div class="lastname" style="margin:10px;">
                <label class="mylastname" style="padding:10px;">Last Name</label>
                <input type="text" name="Contact.LastName" style="margin-left:44px;"  required />
            </div>

            <div class="email" style="margin:10px;">
                <label class="myemail" style="padding:10px;">Email</label>
                <input type="email" style="margin-left:82px;" name="Contact.Email" required />
            </div>

            <div class="title" style="margin:10px;">
                <label class="mytitle" style="padding:10px;">Title</label>
                <select id="title" style="margin-left:90px; width:192px;" name="Contact.Title">
                    <option value="Mr">Mr</option>
                    <option value="Miss" selected>Miss</option>
                    <option value="Mrs">Mrs</option>
                </select>
            </div>

            <div class="description" style="margin:10px;">
                <label class="mydescription" style="display:inline-block; text-align: right; padding-left:10px;">Description</label>
                <textarea id="description" placeholder="Enter your description here ...." style="margin-left:51px;  display: inline-block;
                  vertical-align: top;" rows="5" cols="50" name="Contact.Description"></textarea>
            </div>

            <div class="dateofbirth" style="margin:15px;">
                <label class="mydateofbirth" style="padding-left:3px;">Date of Birth</label>
                <input type="date" style="margin-left:44px;" name="Contact.BirthDate" required />
            </div>

            <div class="marriage" style="margin:10px;">
                <label class="mystatus" style="padding:9px;">Marriage Status</label>
                <select id="marriage" style="margin-left:17px; width:192px;" name="Contact.MarriageStatus">
                    <option value="true">Yes</option>
                    <option value="false">No</option>
                </select>
            </div>

            <div class="username" style="margin:10px;">
                <label class="myusername" style="padding:10px;">Username</label>
                <input type="text" name="Contact.Username" style="margin-left:55px;" required />
            </div>

            <div class="password" style="margin:10px;">
                <label class="mypassword" style="padding:10px;">Password</label>
                <input type="password" name="Contact.Password" style="margin-left:58px;" required />
            </div>

            <div class="role" style="margin:10px;">
                <label class="myrole" style="padding:9px;">Specify Role</label>
                <select id="role" style="margin-left:40px; width:192px;" name="Contact.Role">
                    <option value="Admin">Admin</option>
                    <option value="User">User</option>
                </select>
            </div>

            <div class="btn">
                <button type="submit" class="btn btn-primary">Add Contact</button>
            </div>
        </form>

    </div>
</div>

ContactDatabase/Pages/EditContact.cshtml
@page "/EditContact"
@model ContactDatabase.Pages.EditContactModel
@{
}
<div class="row">
    <div class="col-lg-9 mx-auto rounded border p-3">
        <h2 style="padding:15px;">Edit Contact</h2>
        <form method="post" asp-page-handler="EditContact">
            <input type="hidden" name="id" value="@Model.EditingContact.Id" />
            <div class="firstname" style="margin:10px;">
                <label class="myfirstname" style="padding:10px;">First Name </label>
                <input type="text" name="EditingContact.FirstName" value="@Model.EditingContact.FirstName" style="margin-left:44px;" required />
            </div>

            <div class="lastname" style="margin:10px;">
                <label class="mylastname" style="padding:10px;">Last Name</label>
                <input type="text" name="EditingContact.LastName" value="@Model.EditingContact.LastName" style="margin-left:44px;" required />
            </div>

            <div class="email" style="margin:10px;">
                <label class="myemail" style="padding:10px;">Email</label>
                <input type="email" style="margin-left:82px;" name="EditingContact.Email" value="@Model.EditingContact.Email" required />
            </div>

            <div class="title" style="margin:10px;">
                <label class="mytitle" style="padding:10px;">Title</label>
                <select id="title" style="margin-left:90px; width:192px;" name="EditingContact.Title">
                    @if (Model.EditingContact.Title=="Mr")
                    {
                        <option value="Mr" selected>Mr</option>
                        <option value="Miss">Miss</option>
                        <option value="Mrs">Mrs</option>
                    }
                    else if (Model.EditingContact.Title == "Miss")
                    {
                        <option value="Mr">Mr</option>
                        <option value="Miss" selected>Miss</option>
                        <option value="Mrs">Mrs</option>
                    }
                    else
                    {
                        <option value="Mr">Mr</option>
                        <option value="Miss">Miss</option>
                        <option value="Mrs" selected>Mrs</option>
                    }
                </select>
            </div>

            <div class="description" style="margin:10px;">
                <label class="mydescription" style="display:inline-block; text-align: right; padding-left:10px;">Description</label>
                <textarea id="description"  style="margin-left:51px;  display: inline-block;
                  vertical-align: top;" rows="5" cols="50" name="EditingContact.Description">@Model.EditingContact.Description </textarea>
            </div>

            <div class="dateofbirth" style="margin:15px;">
                <label class="mydateofbirth" style="padding-left:3px;">Date of Birth</label>
                <input type="date" style="margin-left:44px;" name="EditingContact.BirthDate" value="@Model.EditingContact.BirthDate" required />
            </div>

            <div class="marriage" style="margin:10px;">
                <label class="mystatus" style="padding:9px;">Marriage Status</label>
                <select id="marriage" style="margin-left:17px; width:192px;" name="EditingContact.MarriageStatus">
                    @if(Model.EditingContact.MarriageStatus)
                    {
                        <option value="true" selected>Yes</option>
                        <option value="false">No</option>
                    }
                    else
                    {
                        <option value="true">Yes</option>
                        <option value="false" selected>No</option>
                    }
                </select>
            </div>

            <div class="username" style="margin:10px;">
                <label class="myusername" style="padding:10px;">Username</label>
                <input type="text" name="EditingContact.Username" style="margin-left:55px;" value="@Model.EditingContact.Username" required />
            </div>

            <div class="password" style="margin:10px;">
                <label class="mypassword" style="padding:10px;">Password</label>
                <input type="password" name="EditingContact.Password" style="margin-left:58px;" required />
            </div>

            <div class="role" style="margin:10px;">
                <label class="myrole" style="padding:9px;">Specify Role</label>
                <select id="role" style="margin-left:40px; width:192px;" name="EditingContact.Role" value="@Model.EditingContact.Role">
                    <option value="Admin">Admin</option>
                    <option value="User">User</option>
                </select>
            </div>

            <div class="btn">
                <button type="submit" class="btn btn-primary">Edit Contact</button>
            </div>
        </form>
    </div>
</div>

ContactDatabase/Pages/Index.cshtml
@page "/"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@if (!User.Identity.IsAuthenticated)
{
<div class="row" >
    <div class="col-lg-9 mx-auto rounded border p-3">
        <h2 style="padding:15px;">Sign in </h2>
        <form method="post">
            <div class="username" style="margin:10px;">
                <label class="myusername" style="padding:10px;">Username</label>
                <input type="text" name="LoginInput.UserName" style="margin-left:55px;" required />
            </div>

            <div class="password" style="margin:10px;">
                <label class="mypassword" style="padding:10px;">Password</label>
                <input type="password" name="LoginInput.Password" style="margin-left:58px;" required />
            </div>

            <div class="btn">
                <button type="submit" class="btn btn-primary">Login </button>
            </div>
                <div asp-validation-summary="ModelOnly" class="text-danger no-bullet" style="width:300px; ">
                </div>
                <style>
                    .no-bullet ul, .no-bullet ol {
                        list-style: none;
                    }
                </style>
        </form>

    </div>
    </div>

}
else
{
    Response.Redirect("/ContactList");
}